hitchhound/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404

from issues import views as issues_views
from users import views as users_views
from projects import views as project_views
from notifications import views as notification_views
from reporting import views as reporting_views
from hitchhound import views as hitchhound_views

# Custom 404 error handler
handler404 = hitchhound_views.custom_404

urlpatterns = [
    # Admin route
    path('admin/', admin.site.urls),

    # User app routes
    path('accounts/login/', users_views.user_login, name='login'),
    path('signup/', users_views.user_signup, name='signup'),
    path('password_reset/done/', users_views.password_reset_done,
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', users_views.password_reset_done,
         name='password_reset_confirm'),
    path('reset/done/', users_views.password_reset_complete,
         name='password_reset_complete'),
    path('profile/', users_views.user_profile, name='profile'),
    path('change_password/', users_views.change_password,
         name='change_password'),
    path('accounts/', include('django.contrib.auth.urls')),

    # Issue app routes
    path('', issues_views.list_issues, name='home'),
    path('issues/', issues_views.list_issues, name='issues'),
    path('create_issue/', issues_views.create_issue, name='create_issue'),
    path('issues/<int:id>/', issues_views.issue_detail, name='issue_detail'),
    path('issues/<int:id>/edit/', issues_views.edit_issue, name='edit_issue'),
    path('issues/<int:id>/delete/', issues_views.delete_issue,
         name='delete_issue'),
    path('issues/<int:issue_id>/add_comment/', issues_views.add_comment,
         name='add_comment'),

    # Project app routes
    path('projects/', project_views.list_projects, name='projects'),
    path(
        'projects/<int:project_id>/issues/',
        project_views.view_all_issues,
        name='view_all_issues'
    ),
    path('create_project/', project_views.create_project,
         name='create_project'),
    path('edit_project/<int:id>/', project_views.edit_project,
         name='edit_project'),
    path('projects/<int:id>/delete/', project_views.delete_project,
         name='delete_project'),

    # Notification app routes
    path('notifications/', notification_views.list_notifications,
         name='notifications'),
    path(
        'change_history/<int:issue_id>/',
        notification_views.change_history,
        name='issue_change_history'
    ),

    # Reporting app routes
    path(
        'reports/issue_listing_by_status/',
        reporting_views.issue_listing_by_status,
        name='issue_listing_by_status'
    ),
    path(
        'reports/issue_status_summary/',
        reporting_views.issue_status_summary,
        name='issue_status_summary'
    ),
    path(
        'reports/issue_severity_summary/',
        reporting_views.issue_severity_summary,
        name='issue_severity_summary'
    ),
    path(
        'reports/issue_listing_by_assignee/',
        reporting_views.issue_listing_by_assignee,
        name='issue_listing_by_assignee'
    ),
]

issues/models.py
from django.db import models
from projects.models import Project
from users.models import User


class Issue(models.Model):
    """
    This model represents an issue with various attributes, which is assigned
    to a project.
    """
    SEVERITY_CHOICES = (
        (1, '1 - Critical'),
        (2, '2 - High'),
        (3, '3 - Medium'),
        (4, '4 - Low'),
    )
    TYPE_CHOICES = (
        ('bug', 'Bug'),
        ('missed_requirement', 'Missed Requirement'),
        ('other', 'Other Issue'),
    )
    STATUS_CHOICES = (
        ('open', 'Open'),
        ('in_progress', 'In Progress'),
        ('testing', 'Testing'),
        ('approved', 'Approved'),
        ('closed', 'Closed'),
        ('cancelled', 'Cancelled'),
    )

    title = models.CharField(max_length=255, null=False)
    description = models.TextField()
    severity = models.IntegerField(choices=SEVERITY_CHOICES, default=4)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=False)
    type = models.CharField(
        max_length=20, choices=TYPE_CHOICES, default='bug'
    )
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default='open'
    )
    reporter = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='reported_issues'
    )
    developer = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True,
        limit_choices_to={'role': 'developer'}, related_name='developer_issues'
    )
    quality_assurance = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True,
        limit_choices_to={'role': 'quality_assurance'},
        related_name='qa_issues'
    )
    product_manager = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True,
        limit_choices_to={'role': 'product_manager'}, related_name='pm_issues'
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True,
        related_name='updated_issues'
    )

    def get_allowed_statuses_for_role(self, role):
        """
        Return a list of allowed statuses for a given role to power permissions
        """
        if role == 'developer':
            return ['open', 'in_progress']
        elif role == 'quality_assurance':
            return ['open', 'testing']
        elif role == 'product_manager':
            return ['open', 'approved', 'closed', 'cancelled']
        elif role == 'superuser':
            return [
                'open', 'in_progress', 'testing',
                'approved', 'closed', 'cancelled'
            ]
        return ['open']

    def can_user_update_status(self, user, new_status):
        """ Check if a user has permission to update the issue status """
        if user is None:
            return False
        if user.is_superuser:
            return True
        role = user.role
        allowed_statuses = self.get_allowed_statuses_for_role(role)
        print(
            f'User Role: {role}, Attempted Status: {new_status}, '
            f'Allowed Statuses: {allowed_statuses}'
        )

        return new_status in allowed_statuses

    def save(self, *args, **kwargs):
        """
        Override save method to include custom logic for updating the issue.

        If a user is provided via kwargs, set the `updated_by` field to that
        user. Before saving, if the status of the issue is being changed,
        verify that the user has the necessary permissions to change to the new
        status. If the user lacks the required permissions, the save operation
        is aborted.
        """
        user = kwargs.pop('user', None)
        if user:
            self.updated_by = user

        # Only enforce permissions if the status is being changed
        if self.pk:
            old_issue = Issue.objects.get(pk=self.pk)
            if old_issue.status != self.status:
                if not self.can_user_update_status(user, self.status):
                    return False

        super().save(*args, **kwargs)
        return True


class UserIssue(models.Model):
    """
    Intermediate model to link users to specific roles on specific issues.
    """
    ROLE_CHOICES = (
        ('developer', 'Developer'),
        ('quality_assurance', 'Quality Assurance'),
        ('product_manager', 'Product Manager'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    issue = models.ForeignKey(Issue, on_delete=models.CASCADE)
    role = models.CharField(max_length=20, choices=ROLE_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        """ Ensure unique assignments of user to issue with a specific role """
        unique_together = ('user', 'issue', 'role')


class Comment(models.Model):
    """ This model represents a comment made on an issue """
    comment_text = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    issue = models.ForeignKey(Issue, on_delete=models.CASCADE)
    commented_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """ Return a truncated string representation of the comment """
        return self.comment_text[:20]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group
from django.contrib.auth.models import UserManager as DefaultUserManager


class UserManager(DefaultUserManager):
    """
    Custom manager for User model with methods to filter users by role.
    """
    def developers(self):
        return self.filter(role='developer')

    def quality_assurance(self):
        return self.filter(role='quality_assurance')

    def product_managers(self):
        return self.filter(role='product_manager')


class User(AbstractUser):
    """
    Custom user model extending Django's AbstractUser.
    Adds a role field and last_visited_notifications field.
    """
    ROLE_CHOICES = (
        ('developer', 'Developer'),
        ('quality_assurance', 'Quality Assurance'),
        ('product_manager', 'Product Manager'),
    )
    role = models.CharField(
        max_length=20, null=False, choices=ROLE_CHOICES, default='developer'
    )
    last_visited_notifications = models.DateTimeField(null=True, blank=True)
    email = models.EmailField(unique=True)

    objects = UserManager()

    def __str__(self):
        """
        Return the string representation of the user, which is the username.
        """
        return self.username

    def save(self, *args, **kwargs):
        """
        Override the save method to assign the user to a group based on their
        role.
        """
        super().save(*args, **kwargs)
        role_group_map = {
            'developer': 'Developers',
            'quality_assurance': 'Quality Assurance',
            'product_manager': 'Product Managers'
        }
        group_name = role_group_map.get(self.role)
        if group_name:
            group, created = Group.objects.get_or_create(name=group_name)
            self.groups.set([group])

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Row, Column
from users.models import User


class CustomUserCreationForm(UserCreationForm):
    """
    Custom form for creating new users. Extends the default UserCreationForm
    and includes additional fields for first name, last name, email, and role.
    """
    first_name = forms.CharField(
        max_length=30,
        required=True,
        widget=forms.TextInput(
            attrs={'autofocus': 'autofocus'}
        )
    )

    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(required=True)
    role = forms.ChoiceField(choices=User.ROLE_CHOICES, required=True)

    class Meta:
        """
        Meta class to specify the model and fields to include in the form
        """
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'role',
            'password1',
            'password2',
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Remove autofocus from username field
        self.fields['username'].widget.attrs.pop('autofocus', None)


class UserProfileForm(forms.ModelForm):
    """
    Form for updating user profiles. Includes fields for first name, last name,
    and email.
    """
    first_name = forms.CharField(
        max_length=30,
        required=True,
        widget=forms.TextInput(
            attrs={'autofocus': 'autofocus'}
        )
    )
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(required=True)

    class Meta:
        """
        Meta class to specify the model and fields to include in the form
        """
        model = User
        fields = ['first_name', 'last_name', 'email']

    def __init__(self, *args, **kwargs):
        """
        Initialize the form and set up the Crispy Forms helper for better form
        layout.
        """
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
            Row(
                Column('first_name', css_class='form-group col-md-6 mb-0'),
                Column('last_name', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            'email',
            'role',
        )
        self.helper.add_input(Submit('submit', 'Save Changes'))

users/templates/change_password.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block nav_icons %}
{% include 'nav_icons.html' %}
{% endblock %}


{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center my-5">
        <div class="col-lg-6 col-md-8 col-sm-10 col-12">
            <div class="card">
                <div class="card-header">
                    <h2>Change Password</h2>
                </div>
                <div class="card-body">
                    <!-- Form for changing password -->
                    <form method="post" action="{% url 'change_password' %}" id="password-change-form">
                        {% csrf_token %}
                        {{ password_change_form|crispy }}
                        <div class="row mt-3">
                            <div class="col-12 col-sm-6 mb-2 mb-sm-0">
                                <button type="submit" class="btn btn-success w-100" id="save-password-btn"
                                    name="save_password">Save New Password</button>
                            </div>
                            <div class="col-12 col-sm-6">
                                <button type="button" class="btn btn-secondary w-100"
                                    onclick="window.history.back();">Cancel</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'new_item_modal.html' %}
{% include 'logout_modal.html' %}

{% endblock %}

{% block extra_js %}
{% include 'base_extra_js.html' %}
{% endblock %}

users/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center my-5">
        <div class="col-lg-6 col-md-8 col-sm-10 col-12">
            <div class="card">
                <div class="card-header">
                    <h2>Login</h2>
                </div>
                <!-- Alert Placeholder -->
                {% if error_message %}
                <div class="alert alert-danger" role="alert">
                    {{ error_message }}
                </div>
                {% endif %}
                <div class="card-body">
                    <!-- Form for logging in -->
                    <form method="post" action="{% url 'login' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username">Username:</label>
                            <input type="text" id="username" name="username" class="form-control mb-3" autofocus>
                        </div>
                        <div class="form-group">
                            <label for="password">Password:</label>
                            <input type="password" id="password" name="password" class="form-control mb-3">
                        </div>
                        <div class="row">
                            <div class="col-12 col-sm-6 mb-2 mb-sm-0">
                                <button type="submit" class="btn btn-primary w-100">Login</button>
                            </div>
                            <div class="col-12 col-sm-6">
                                <a href="{% url 'password_reset' %}" class="btn btn-secondary w-100" id="forgot">Forgot
                                    your password?</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_js %}
<script src="{% static 'js/alert.js' %}"></script>
{% endblock %}

users/templates/logout.html
{% extends 'base.html' %}

{% block nav-icons %}
{% endblock %}

{% block nav %}
<li class="nav-item {% if active_page == 'issues' %}active{% endif %}">
    <a class="nav-link" href="{% url 'issues' %}">Issues{% if active_page == 'issues' %}<span class="sr-only">(current)</span>{% endif %}</a>
</li>
<li class="nav-item {% if active_page == 'projects' %}active{% endif %}">
    <a class="nav-link" href="{% url 'projects' %}">Projects{% if active_page == 'projects' %}<span class="sr-only">(current)</span>{% endif %}</a>
</li>
<li class="nav-item {% if active_page == 'reports' %}active{% endif %}">
    <a class="nav-link" href="{% url 'reports' %}">Reports{% if active_page == 'reports' %}<span class="sr-only">(current)</span>{% endif %}</a>
</li>
<li class="nav-item {% if active_page == 'profile' %}active{% endif %}">
    <a class="nav-link" href="{% url 'profile' %}">Profile{% if active_page == 'profile' %}<span class="sr-only">(current)</span>{% endif %}</a>
</li>
<li class="nav-item {% if active_page == 'logout' %}active{% endif %}">
    <a class="nav-link" href="{% url 'logout' %}">Logout{% if active_page == 'logout' %}<span class="sr-only">(current)</span>{% endif %}</a>
</li>
{% endblock %}

{% block content %}
<h1>Logout</h1>
<p>This is the logout page.</p>
{% endblock %}

users/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block nav_icons %}
{% include 'nav_icons.html' %}
{% endblock %}

{% block content %}

<div class="container mt-4">
    <h2>User Profile for {{ username }}</h2>
    <!-- Alert Placeholder -->
    <div id="live-alert-placeholder"></div>
    <div class="row mt-5 justify-content-center">
        <div class="col-lg-6 col-md-8 col-12">
            <div class="card h-100">
                <div class="card-body d-flex flex-column justify-content-between">
                    <!-- User details form -->
                    <form method="post" id="profile-form" class="h-100 d-flex flex-column">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <!-- Display the user's role -->
                        <div class="form-group mb-4">
                            <label>Role:</label>
                            <span class="form-control-plaintext" style="display: inline;">{{ form.instance.get_role_display }}</span>
                            <small class="form-text text-muted" style="display: block;">If you need to change your role, please contact an admin.</small>
                        </div>
                        <div class="mt-auto">
                            <!-- Buttons for editing profile and changing password -->
                            <div class="row mb-2" id="static-buttons">
                                <div class="col-12 col-md-6 mb-2 mb-md-0">
                                    <button type="button" class="btn btn-custom w-100" id="edit-btn" onclick="toggleProfileEditMode()">Edit</button>
                                </div>
                                <div class="col-12 col-md-6">
                                    <a href="{% url 'change_password' %}" class="btn btn-primary w-100" id="change-password-btn">Change Password</a>
                                </div>
                            </div>
                            <!-- Buttons for saving and cancelling when in edit mode -->
                            <div id="edit-mode-buttons" class="row d-none mt-3">
                                <div class="col-12 col-md-6 mb-2 mb-md-0">
                                    <button type="submit" class="btn btn-success w-100" id="save-btn" name="save_profile">Save Changes</button>
                                </div>
                                <div class="col-12 col-md-6">
                                    <button type="button" class="btn btn-secondary w-100" id="cancel-btn" onclick="toggleProfileEditMode()">Cancel</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- User's issues section -->
<div class="row mt-5">
    <div class="col-12">
        <h2>Your Issues</h2>
        <div class="table-responsive">
            <table class="table table-hover table-bordered">
                <thead>
                    <tr class="table-secondary">
                        <!-- Column headers with sorting links -->
                        <th scope="col">
                            <a href="?sort_by=id&order={{ toggle_order }}" class="text-dark text-decoration-none">
                                Issue ID
                                <i
                                    class="fa {% if sort_by == 'id' %}{% if order == 'asc' %}fa-arrow-up{% else %}fa-arrow-down{% endif %} text-dark{% else %}fa-arrow-up text-muted{% endif %}"></i>
                            </a>
                        </th>
                        <th scope="col">
                            <a href="?sort_by=title&order={{ toggle_order }}" class="text-dark text-decoration-none">
                                Title
                                <i
                                    class="fa {% if sort_by == 'title' %}{% if order == 'asc' %}fa-arrow-up{% else %}fa-arrow-down{% endif %} text-dark{% else %}fa-arrow-up text-muted{% endif %}"></i>
                            </a>
                        </th>
                        <th scope="col">
                            <a href="?sort_by=severity&order={{ toggle_order }}" class="text-dark text-decoration-none">
                                Severity
                                <i
                                    class="fa {% if sort_by == 'severity' %}{% if order == 'asc' %}fa-arrow-up{% else %}fa-arrow-down{% endif %} text-dark{% else %}fa-arrow-up text-muted{% endif %}"></i>
                            </a>
                        </th>
                        <th scope="col" class="d-none d-md-table-cell">
                            <a href="?sort_by=type&order={{ toggle_order }}" class="text-dark text-decoration-none">
                                Type
                                <i
                                    class="fa {% if sort_by == 'type' %}{% if order == 'asc' %}fa-arrow-up{% else %}fa-arrow-down{% endif %} text-dark{% else %}fa-arrow-up text-muted{% endif %}"></i>
                            </a>
                        </th>
                        <th scope="col" class="d-none d-md-table-cell">
                            <a href="?sort_by=project&order={{ toggle_order }}" class="text-dark text-decoration-none">
                                Project
                                <i
                                    class="fa {% if sort_by == 'project' %}{% if order == 'asc' %}fa-arrow-up{% else %}fa-arrow-down{% endif %} text-dark{% else %}fa-arrow-up text-muted{% endif %}"></i>
                            </a>
                        </th>
                        <th scope="col" class="d-none d-md-table-cell">
                            <a href="?sort_by=status&order={{ toggle_order }}" class="text-dark text-decoration-none">
                                Status
                                <i
                                    class="fa {% if sort_by == 'status' %}{% if order == 'asc' %}fa-arrow-up{% else %}fa-arrow-down{% endif %} text-dark{% else %}fa-arrow-up text-muted{% endif %}"></i>
                            </a>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <!-- Loop through the user's issues -->
                    {% for issue in page_obj %}
                    <tr class="table-light" onclick="window.location.href='{% url 'issue_detail' issue.id %}'"
                        style="cursor: pointer;">
                        <td>#{{ issue.id }}</td>
                        <td>{{ issue.title|truncatechars:50 }}</td>
                        <td>{{ issue.get_severity_display }}</td>
                        <td class="d-none d-md-table-cell">{{ issue.get_type_display }}</td>
                        <td class="d-none d-md-table-cell">{{ issue.project.title }}</td>
                        <td class="d-none d-md-table-cell">{{ issue.get_status_display }}</td>
                    </tr>
                    {% empty %}
                    <tr>
                        <!-- Message displayed if there are no issues -->
                        <td colspan="6">You don't have any issues assigned to you.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% include 'pagination.html' %}

{% include 'new_item_modal.html' %}
{% include 'logout_modal.html' %}

{% endblock %}

{% block extra_js %}
{% include 'base_extra_js.html' %}
<script src="{% static 'js/toggle_edit_mode.js' %}"></script>
{% if alert_type %}
<script>
    sessionStorage.setItem('Alert Type', '{{ alert_type }}');
</script>
{% endif %}
<script src="{% static 'js/alert.js' %}"></script>
{% endblock %}

users/templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block nav %}
<!-- Navigation for just this page to direct user to login page instead -->
<li class="nav-item">
    <a class="nav-link" href="{% url 'login' %}">Already registered? <span id="login">Login</span></a>
</li>
{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="row justify-content-center my-5">
        <div class="col-lg-6 col-md-8 col-sm-10 col-12">
            <div class="card">
                <div class="card-header">
                    <h2>Register</h2>
                </div>
                <div class="card-body">
                    <!-- Form for user registration -->
                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <p> * mandatory field </p>
                        <button type="submit" class="btn btn-custom w-100">Register</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}